risechain/pevm

Cargo.lock
Cargo.toml
README.md
src/block_stm.rs
src/lib.rs
src/main.rs
src/mv_memory.rs
src/scheduler.rs
src/vm.rs

...to avoid "implicit" dependency among consecutive transactions.

Lazy update beneficiary balance 

---

Cargo.lock
Cargo.toml
src/block_stm.rs
src/lib.rs
src/primitives.rs
tests/beneficiary.rs
tests/common/mod.rs
tests/common/runner.rs
tests/erc20/main.rs
tests/ethereum/main.rs
tests/raw_transfers.rs
tests/uniswap/main.rs

Execute alloy blocks

---

src/pevm.rs

Avoids overflowing the stack in debug mode, while it's the same on release

chore: remove recursion from try_execute

---

src/pevm.rs
src/storage/rpc.rs
src/vm.rs

Extracted from https://github.com/risechain/pevm/pull/150

chore: minor refactorings

---

src/pevm.rs
src/vm.rs

One step towards https://github.com/risechain/pevm/issues/60.

feat: generalize reward policy to support other chains

---

src/pevm.rs
src/storage/rpc.rs

one step toward https://github.com/risechain/pevm/issues/60

feat: unify logic to handle rewarded accounts (beneficiary account and lazy recipients)

---

src/pevm.rs
src/vm.rs

- ~use while let to make code clear~ (There is a problem)
- typo fix

chore: typo fix

---

src/pevm.rs
src/storage.rs
tests/mainnet.rs

refactor: let StorageWrapper accepts a reference

---

src/chain.rs
src/chain/ethereum.rs
src/vm.rs

refactor: add get_handler in trait PevmChain

---

src/chain.rs
src/chain/ethereum.rs
src/vm.rs

refactor: add get_reward_policy in trait PevmChain

---

src/storage/rpc.rs
tests/mainnet.rs

Partially resolves https://github.com/risechain/pevm/issues/202

feat: deduplicate bytecodes in RpcStorage

---

benches/gigagas.rs
src/lib.rs
src/storage.rs
src/storage/in_memory.rs
tests/beneficiary.rs
tests/common/mod.rs
tests/erc20/main.rs
tests/erc20/mod.rs
tests/ethereum/main.rs
tests/mixed.rs
tests/raw_transfers.rs
tests/small_blocks.rs
tests/uniswap/main.rs
tests/uniswap/mod.rs

Partially resolves https://github.com/risechain/pevm/issues/202

feat: deduplicate bytecodes in InMemoryStorage

---

benches/gigagas.rs

fix typos Benchemark --- Benchmark

fix typos Benchemark --- Benchmark

---

benches/mainnet.rs

Benchemark -----Benchmark fix : typo

Benchemark -----Benchmark

---

src/chain.rs
src/chain/ethereum.rs
src/pevm.rs
src/vm.rs

We move the EIP check to PevmChain so that we can customize other chains.

feat: check EIPs in PevmChain

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/chain.rs
src/chain/ethereum.rs
src/chain/optimism.rs
src/vm.rs
tests/ethereum/main.rs
tests/raw_transfers.rs

Resolves https://github.com/risechain/pevm/issues/60

feat: support optimism

---

src/storage/rpc.rs

impl has_storage

---

src/lib.rs
src/pevm.rs
src/vm.rs

This PR addresses https://github.com/risechain/pevm/issues/318

chore(`vm`): rewrite `VmExecutionResult` as `Result`

---

Cargo.lock
Cargo.toml
README.md
bin/fetch.rs
tests/mainnet.rs

This PR addresses https://github.com/risechain/pevm/issues/249.

 feat(`cli`): move snapshot functionality to a cli

---

src/pevm.rs
src/vm.rs
tests/ethereum/main.rs

Closes https://github.com/risechain/pevm/issues/311
Replaced general addition and subtraction with `saturating_add()` and `saturating_sub()` to most places as required

feat:prevent overflow and underflow

---

Cargo.lock
Cargo.toml
src/chain/ethereum.rs
src/chain/optimism.rs
tests/ethereum/main.rs

chore: translate authorization list from alloy transactions to revm's TxEnv

---

.github/workflows/fmt.yml
.github/workflows/lint.yml

ci: add formatting check

---

src/chain/optimism.rs

Resolves https://github.com/risechain/pevm/issues/396
**Usage**
```
PevmOptimism::custom(901u64)
```

feat: allow custom chain id

---

src/pevm.rs
tests/ethereum/main.rs

Resolves https://github.com/risechain/pevm/issues/397

fix: do not panic in nonce check

---

Cargo.lock
crates/pevm/Cargo.toml
crates/pevm/src/chain/ethereum.rs
crates/pevm/src/chain/optimism.rs

refactor: hardcode Ethereum & OP chain ids(#421)

---

.github/workflows/ci.yml

CI: Add cargo-machete (#420)

---

Cargo.lock
Cargo.toml
bins/fetch/Cargo.toml
bins/fetch/src/main.rs
crates/pevm/Cargo.toml
crates/pevm/src/chain.rs
crates/pevm/src/chain/ethereum.rs
crates/pevm/src/chain/optimism.rs
crates/pevm/src/compat.rs
crates/pevm/src/pevm.rs
crates/pevm/src/storage/rpc.rs
crates/pevm/src/vm.rs
crates/pevm/tests/common/mod.rs
crates/pevm/tests/common/runner.rs
crates/pevm/tests/mainnet.rs

refactor: import specific alloy rpc (#428)

---

.github/workflows/ci.yml
.github/workflows/fmt.yml
Cargo.toml
bins/fetch/Cargo.toml
crates/pevm/Cargo.toml

chore: add reoder_keys option format with taplo into ci

---

crates/pevm/tests/mainnet.rs

test: mainnet_blocks_from_rpc for op
