- src/block_stm.rs
- src/main.rs
- src/vm.rs
Addresses #15.
Also unblocks #18 by providing `Vm` the beneficiary account (`block_env.coinbase`), for it to atomically update beneficiary balance via a custom `PostExecutionHandler::reward_beneficiary`, and to intercept explicit reads (& writes) to wait for all updates of the lower transactions.
> feat: pass BlockEnv into block_stm & vm

- src/block_stm.rs
- src/mv_memory.rs
- src/vm.rs
Evaluating a beneficiary account must read absolute from the adjacent transaction in front. We cannot read optimistically from the closest transaction like in standard BlockSTM.
> Fix reading while lazy evaluating beneficiary account

- src/block_stm.rs
- src/vm.rs
- tests/beneficiary.rs
- tests/common/mod.rs
- tests/raw_transfers.rs
Addresses #16 and enables #5 as we test & sync throughout the eras.
> Pass `SpecId` into `BlockSTM` & `VM`

- src/storage.rs
> Wait longer before an RPC request

- src/lib.rs
- src/mv_memory.rs
- src/pevm.rs
- src/scheduler.rs
- src/storage.rs
- src/vm.rs
- tests/small_blocks.rs
When I read the code of pevm, I found some typo. So I'd like to fix them.
> chore: fix typo in comment

- src/lib.rs
- src/pevm.rs
- src/scheduler.rs
`transactions_dependencies` is just used to determine if a transaction still has predecessor dependencies.
So, we just use a `AtomicUsize` to count its size.
> perf: transactions_dependencies just need count number

- Cargo.lock
- Cargo.toml
- benches/gigagas.rs
- benches/mainnet.rs
- src/pevm.rs
- src/vm.rs
- tests/beneficiary.rs
- tests/common/runner.rs
- tests/erc20/main.rs
- tests/ethereum/main.rs
- tests/mainnet.rs
- tests/mixed.rs
- tests/raw_transfers.rs
- tests/small_blocks.rs
- tests/uniswap/main.rs
These changes are made to prepare for https://github.com/risechain/pevm/pull/168.
**Before**
```
CfgEnv::default()
```
**After**
```
CfgEnv::default().with_chain_id(chain.id())
```
> refactor: use Chain to set chain_id

- Cargo.lock
- Cargo.toml
- benches/gigagas.rs
- src/storage.rs
- src/storage/rpc.rs
- tests/common/mod.rs
- tests/common/runner.rs
- tests/common/storage.rs
- tests/erc20/contract.rs
- tests/erc20/main.rs
- tests/erc20/mod.rs
- tests/mainnet.rs
- tests/mixed.rs
- tests/uniswap/contract.rs
- tests/uniswap/main.rs
- tests/uniswap/mod.rs
Note: This change is not implemented for accounts on the disk. Accounts are deserialised into `PlainAccount` for now.
Snapshot generation and serialisation of `EvmAccount` types must be done in subsequent PRs.
> Use EvmAccount instead of PlainAccount

- src/storage/rpc.rs
We are gonna have:
```rust
let provider = ProviderBuilder::<_, _, Optimism>::default().on_http(rpc_url.clone());
let rpc_storage =
RpcStorage::new(provider.clone(), spec_id, BlockId::number(block_number - 1));
```
> refactor: parameterize <N: Network> for RpcStorage

- benches/gigagas.rs
- src/lib.rs
- src/pevm.rs
- tests/common/runner.rs
- tests/ethereum/main.rs
On the `optimism` branch, we will have:
```rust
let mv_memory = 'b: {
#[cfg(feature = "optimism")]
if chain.is_optimism() {
break 'b DeferDrop::new(get_optimism_mv_memory(&hasher, &block_env, &txs));
}
DeferDrop::new(get_mv_memory(&hasher, &block_env, &txs))
};
```
> refactor: extract fn get_mv_memory

- benches/gigagas.rs
- tests/common/mod.rs
- tests/common/runner.rs
- tests/raw_transfers.rs
- tests/small_blocks.rs
Test `one_tx_alloy_block` always throw error because of  wrong `nonce`.
> fix: correct nonce in unit test

- src/lib.rs
- src/scheduler.rs
- src/vm.rs
- tests/ethereum/main.rs
use fn push_origin to simplify code
> refactor: use fn push_origin to simplify code

- .github/workflows/ci.yml
- src/storage/rpc.rs
- tests/mainnet.rs
Resolves https://github.com/risechain/pevm/pull/233#discussion_r1745015548
Community PRs are failing CI. It looks like `https://eth.llamarpc.com` does not work anymore (at least in our CI). This PR changes the default value to `https://eth.public-rpc.com`.
This PR also changes the env variable from `RPC_URL` to `ETHEREUM_RPC_URL`. Later we will have `OPTIMISM_RPC_URL`. Note that when the CI runs `cargo test`, both Ethereum and Optimism tests will run, therefore, having one `RPC_URL` is bad.
> feat: resolve error 429 Too Many Requests in CI

- src/chain.rs
- src/chain/ethereum.rs
- src/compat.rs
- src/pevm.rs
- tests/common/runner.rs
Resolves https://github.com/risechain/pevm/pull/233#discussion_r1745009221
> refactor: move to PevmChain::get_tx_env

- src/pevm.rs
> fix: assert account balance and nonce in lazy evaluation

- src/pevm.rs
This PR addresses https://github.com/risechain/pevm/issues/310
> chore(`pevm`): Post-processing lazy evaluation: assert that the evaluated nonce matches the transaction's

- tests/ethereum/main.rs
Closes https://github.com/risechain/pevm/issues/326
Changes:
Function `build_tx_env` now requires a parameter `path`
> fix: Report test name that fails to parse sender address

- src/storage.rs
We only persist `eofheader` and `eofbody` but not `raw`.
> feat: support eof(#316)

- Cargo.lock
- Cargo.toml
- src/storage.rs
- src/vm.rs
- tests/ethereum/main.rs
> refactor: add error handling for Bytecode type

- Cargo.lock
- Cargo.toml
- src/chain.rs
- src/chain/ethereum.rs
- src/chain/optimism.rs
- src/lib.rs
- src/pevm.rs
- src/storage.rs
- src/storage/rpc.rs
- src/vm.rs
- tests/common/mod.rs
- tests/common/storage.rs
- tests/erc20/contract.rs
- tests/erc20/main.rs
- tests/ethereum/main.rs
- tests/mixed.rs
- tests/uniswap/contract.rs
- tests/uniswap/main.rs
A new `HashMap` now should be imported from `hashbrown` and explicitly declared a hasher (`BuildIdentityHasher`, `BuildSuffixHasher`, or `FxBuildHasher` as the default).
> perf: replace `std` `HashMap` with `hashbrown` 15 & `ahash` with `rustc-hash` 2

- src/pevm.rs
- src/vm.rs
`FxBuildHasher` is a ZST, there is no benefit to storing it by reference; even if it was something like a random state it would hold 1 or 2 u64s, which should still be copied rather than passed by reference
> chore: store FxBuildHasher by value

- Cargo.lock
- Cargo.toml
- src/chain/optimism.rs
- tests/common/mod.rs
We need these changes to make sure there is only one version of `alloy-eip7702` in the reth integration. Otherwise, there will be compile errors.
```diff
- op-alloy-consensus = { version = "0.5.0", optional = true }
- op-alloy-network = { version = "0.5.0", optional = true }
- op-alloy-rpc-types = { version = "0.5.0", optional = true }
+ op-alloy-consensus = { version = "0.4.0", optional = true }
+ op-alloy-network = { version = "0.4.0", optional = true }
+ op-alloy-rpc-types = { version = "0.4.0", optional = true }
```
This change is to update `revm` to the [`reth` branch](https://github.com/risechain/revm/commits/reth):
```diff
- revm = { git = "https://github.com/risechain/revm", rev = "bb350a971e5f39a8f822ace081584a3a45fd7c6a", features = [
+ revm = { git = …
```
> feat: downgrade deps to make it compatible to reth 1.1.0

- crates/pevm/tests/mainnet.rs
move some uses to remove annoying warnings
Closes #427
> Move uses to mainnet_blocks_from_rpc

- README.md
- crates/pevm/benches/README.md
- crates/pevm/benches/mainnet.rs
We didn't reproduce the poor benchmark on cloud ARM instances. It turns out to only happen on machines with both performance and efficient cores like my Intel i9-12900K (Alder Lake and hybrid architecture in general). 
The kernel scheduler aggressively scheduled `pevm` worker threads on performance cores before 6.6, but the new scheduler (probably together with Intel driver changes) started to also pick efficient cores. The "fix" is to run the benchmark with `taskset -a -c` only performance cores.
Practically, we should run benchmarks (and performance-critical production code) on machines with all performance cores to not risk the kernel scheduler picking the "wrong" CPU to run a worker thread. 
A more guaranteed solution is to pin worker threads to performance cores right within `pevm`, …
> doc(bench): demystify poor benchmark on new Linux kernel versions

- crates/pevm/tests/snapshot_data.rs
This PR handles #450. 
Please let me know if there are any changes or improvements you'd like me to make.
> Add `snapshot_data.rs`

- crates/pevm/src/chain/ethereum.rs
- crates/pevm/src/chain/optimism.rs
- crates/pevm/src/lib.rs
- crates/pevm/src/pevm.rs
- crates/pevm/src/vm.rs
- **`ethereum.rs` and `optimism.rs`**  
- `"hash_determinisitic"` → `"hash_deterministic"`  
- **`lib.rs`**  
- `"hash_determinisitic"` → `"hash_deterministic"`  
- **`pevm.rs`**  
- `"hash_determinisitic"` → `"hash_deterministic"` in multiple locations  
- **`vm.rs`**  
- `"hash_determinisitic"` → `"hash_deterministic"` in multiple locations
> Fix spelling errors

- bins/fetch/src/main.rs
- crates/pevm/tests/ethereum/main.rs
This PR fixes two typos in code comments:
- Corrects 'Retrive' to 'Retrieve' in bins/fetch/src/main.rs
- Corrects 'exepect' to 'expect' in crates/pevm/tests/ethereum/main.rs
> Fix typos in code comments
